Fix/pm 499 match alive frequency with diagnostics
project-march/input-device pull request #59
Opened 2020-06-30 12:31 UTC by JorisWeeda

Closes PM-499

## Description
Changes the update frequency of the input device crutch alive topic to match the frequency given in the march rqt input device. It seems redundant to have such a high frequency and 5 Hz will be more then sufficient (as it is for the rqt input device). The update loop frequency will remain unchanged but online the _alive_ topic will publish with less of 1/4 times the update frequency

## Changes
* Downscale the update frequency of the _alive_ topic of the crutch input device.
*

2020-07-02 09:08 UTC, RutgerVanBeek submitted a review, later dismissed

2020-07-02 09:09 UTC, Roelemans submitted a review, later dismissed

2020-07-02 09:10 UTC, Roelemans commented
Should be tested before merging

2020-07-10 12:04 UTC, Roelemans submitted a review, later dismissed

2020-07-13 09:22 UTC, Olavhaasie requested changes

2020-07-13 09:22 UTC, Olavhaasie commented on src/main.cpp
> +uint8_t _CURRENT_FLAG_VALUE = 0;
The global values do not have to be preceded by an underscore. Also only `ALIVE_FREQUENCY_PUBLISHER_FLAG` should be upper case and made `const`. This way it is consistent with the rest of the code.
```suggestion
const uint8_t ALIVE_FREQUENCY_PUBLISHER_FLAG = 4;
uint8_t current_flag_value = 0;
```

2020-07-13 11:49 UTC, Olavhaasie approved these changes

2020-07-15 07:59 UTC, merged